In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
df=pd.read_csv('Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [26]:
X=df.iloc[:,3:13]
y=df.iloc[:,13]

In [27]:
 X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [28]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [29]:
geography=pd.get_dummies(X['Geography'],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [30]:
X=pd.concat([X,geography,gender],axis=1)

In [31]:
X=X.drop(['Geography','Gender'],axis=1)

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [33]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [34]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /opt/anaconda3/lib/python3.8/site-packages (2.4.0)
Requirement already satisfied: opt-einsum~=3.3.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: flatbuffers~=1.12.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.12)
Requirement already satisfied: astunparse~=1.6.3 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: absl-py~=0.10 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.11.0)
Requirement already satisfied: six~=1.15.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: termcolor~=1.1.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: numpy~=1.19.2 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.19.5)
Requirement already satisfied: grpcio~=1.32.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.32.0)
Requirement already satisfied: gast==0.3.3 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.3.3)
Requirement already satisfied: wrapt~=1.12.1 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.12.1)
Requirement already satisfied: wheel~=0.35 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: tensorflow-estimator<2.5.0,>=2.4.0rc0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: protobuf>=3.9.2 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (3.13.0)
Requirement already satisfied: google-pasta~=0.2 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: tensorboard~=2.4 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: h5py~=2.10.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: typing-extensions~=3.7.4 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (3.7.4.2)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /opt/anaconda3/lib/python3.8/site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.8/site-packages (from protobuf>=3.9.2->tensorflow) (49.2.0.post20200714)
Requirement already satisfied: google-auth<2,>=1.6.3 in /opt/anaconda3/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (1.24.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /opt/anaconda3/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (0.4.2)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (2.24.0)
Requirement already satisfied: werkzeug>=0.11.15 in /opt/anaconda3/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (1.0.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /opt/anaconda3/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (1.7.0)
Requirement already satisfied: markdown>=2.6.8 in /opt/anaconda3/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (3.3.3)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in /opt/anaconda3/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (4.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (4.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow) (1.3.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/anaconda3/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (3.0.4)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda3/lib/python3.8/site-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow) (3.1.0)

In [39]:
!pip install keras

Collecting keras
  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)
Requirement already satisfied: h5py in /opt/anaconda3/lib/python3.8/site-packages (from keras) (2.10.0)
Requirement already satisfied: numpy>=1.9.1 in /opt/anaconda3/lib/python3.8/site-packages (from keras) (1.19.5)
Requirement already satisfied: scipy>=0.14 in /opt/anaconda3/lib/python3.8/site-packages (from keras) (1.5.0)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.8/site-packages (from keras) (5.3.1)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.8/site-packages (from h5py->keras) (1.15.0)
Installing collected packages: keras
Successfully installed keras-2.4.3

In [35]:
import tensorflow as tf

In [36]:
from tensorflow import keras

In [40]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [47]:
classifier=Sequential()
#Adding the input layer and the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu',input_dim=11))

#Adding the second hidden layer
classifier.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu'))


#Adding the ouput layer
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

#compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [48]:
classifier.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 6)                 72
_________________________________________________________________
dense_7 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

In [51]:
# Fitting the ANN to the Training set
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 2s 3ms/step - loss: 0.5531 - accuracy: 0.7939 - val_loss: 0.4740 - val_accuracy: 0.7955
Epoch 2/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.8067 - val_loss: 0.4501 - val_accuracy: 0.7955
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4249 - accuracy: 0.8039 - val_loss: 0.4354 - val_accuracy: 0.7955
Epoch 4/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4294 - accuracy: 0.7883 - val_loss: 0.4264 - val_accuracy: 0.7955
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4068 - accuracy: 0.8044 - val_loss: 0.4184 - val_accuracy: 0.8217
Epoch 6/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4137 - accuracy: 0.8130 - val_loss: 0.4098 - val_accuracy: 0.8262
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3985 - accuracy: 0.8275 - val_loss: 0.4033 - val_accuracy: 0.8307
Epoch 8/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3809 - accuracy: 0.8383 - val_loss: 0.3980 - val_accuracy: 0.8304
Epoch 9/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3775 - accuracy: 0.8422 - val_loss: 0.3941 - val_accuracy: 0.8292
Epoch 10/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3734 - accuracy: 0.8441 - val_loss: 0.3904 - val_accuracy: 0.8330
Epoch 11/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3661 - accuracy: 0.8484 - val_loss: 0.3879 - val_accuracy: 0.8326
Epoch 12/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3665 - accuracy: 0.8484 - val_loss: 0.3843 - val_accuracy: 0.8353
Epoch 13/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3676 - accuracy: 0.8518 - val_loss: 0.3812 - val_accuracy: 0.8391
Epoch 14/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3674 - accuracy: 0.8483 - val_loss: 0.3780 - val_accuracy: 0.8406
Epoch 15/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3660 - accuracy: 0.8500 - val_loss: 0.3748 - val_accuracy: 0.8455
Epoch 16/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3731 - accuracy: 0.8458 - val_loss: 0.3735 - val_accuracy: 0.8489
Epoch 17/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3425 - accuracy: 0.8595 - val_loss: 0.3704 - val_accuracy: 0.8493
Epoch 18/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3543 - accuracy: 0.8574 - val_loss: 0.3691 - val_accuracy: 0.8508
Epoch 19/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3604 - accuracy: 0.8535 - val_loss: 0.3695 - val_accuracy: 0.8497
Epoch 20/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3599 - accuracy: 0.8490 - val_loss: 0.3675 - val_accuracy: 0.8493
Epoch 21/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3475 - accuracy: 0.8624 - val_loss: 0.3658 - val_accuracy: 0.8512
Epoch 22/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3318 - accuracy: 0.8688 - val_loss: 0.3650 - val_accuracy: 0.8504
Epoch 23/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3417 - accuracy: 0.8628 - val_loss: 0.3645 - val_accuracy: 0.8519
Epoch 24/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3531 - accuracy: 0.8581 - val_loss: 0.3655 - val_accuracy: 0.8501
Epoch 25/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3489 - accuracy: 0.8534 - val_loss: 0.3660 - val_accuracy: 0.8497
Epoch 26/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3472 - accuracy: 0.8522 - val_loss: 0.3634 - val_accuracy: 0.8504
Epoch 27/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3300 - accuracy: 0.8648 - val_loss: 0.3627 - val_accuracy: 0.8523
Epoch 28/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3401 - accuracy: 0.8624 - val_loss: 0.3628 - val_accuracy: 0.8519
Epoch 29/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3318 - accuracy: 0.8642 - val_loss: 0.3616 - val_accuracy: 0.8538
Epoch 30/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3401 - accuracy: 0.8619 - val_loss: 0.3620 - val_accuracy: 0.8527
Epoch 31/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3334 - accuracy: 0.8609 - val_loss: 0.3622 - val_accuracy: 0.8542
Epoch 32/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3430 - accuracy: 0.8605 - val_loss: 0.3616 - val_accuracy: 0.8508
Epoch 33/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3388 - accuracy: 0.8655 - val_loss: 0.3612 - val_accuracy: 0.8538
Epoch 34/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3327 - accuracy: 0.8625 - val_loss: 0.3606 - val_accuracy: 0.8557
Epoch 35/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3406 - accuracy: 0.8618 - val_loss: 0.3595 - val_accuracy: 0.8561
Epoch 36/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8610 - val_loss: 0.3593 - val_accuracy: 0.8535
Epoch 37/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8613 - val_loss: 0.3592 - val_accuracy: 0.8550
Epoch 38/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8582 - val_loss: 0.3586 - val_accuracy: 0.8538
Epoch 39/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3399 - accuracy: 0.8650 - val_loss: 0.3590 - val_accuracy: 0.8523
Epoch 40/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8637 - val_loss: 0.3579 - val_accuracy: 0.8573
Epoch 41/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3324 - accuracy: 0.8642 - val_loss: 0.3583 - val_accuracy: 0.8542
Epoch 42/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3416 - accuracy: 0.8582 - val_loss: 0.3578 - val_accuracy: 0.8538
Epoch 43/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3313 - accuracy: 0.8703 - val_loss: 0.3592 - val_accuracy: 0.8561
Epoch 44/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3447 - accuracy: 0.8525 - val_loss: 0.3579 - val_accuracy: 0.8535
Epoch 45/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3444 - accuracy: 0.8591 - val_loss: 0.3607 - val_accuracy: 0.8531
Epoch 46/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3356 - accuracy: 0.8574 - val_loss: 0.3577 - val_accuracy: 0.8554
Epoch 47/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8572 - val_loss: 0.3562 - val_accuracy: 0.8542
Epoch 48/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3383 - accuracy: 0.8586 - val_loss: 0.3567 - val_accuracy: 0.8546
Epoch 49/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3248 - accuracy: 0.8699 - val_loss: 0.3569 - val_accuracy: 0.8569
Epoch 50/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3305 - accuracy: 0.8642 - val_loss: 0.3565 - val_accuracy: 0.8546
Epoch 51/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8611 - val_loss: 0.3564 - val_accuracy: 0.8538
Epoch 52/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8693 - val_loss: 0.3559 - val_accuracy: 0.8557
Epoch 53/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3306 - accuracy: 0.8654 - val_loss: 0.3572 - val_accuracy: 0.8538
Epoch 54/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3249 - accuracy: 0.8653 - val_loss: 0.3556 - val_accuracy: 0.8542
Epoch 55/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8556 - val_loss: 0.3563 - val_accuracy: 0.8554
Epoch 56/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3278 - accuracy: 0.8724 - val_loss: 0.3557 - val_accuracy: 0.8557
Epoch 57/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3265 - accuracy: 0.8659 - val_loss: 0.3557 - val_accuracy: 0.8550

Epoch 58/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3301 - accuracy: 0.8632 - val_loss: 0.3558 - val_accuracy: 0.8523
Epoch 59/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3279 - accuracy: 0.8665 - val_loss: 0.3564 - val_accuracy: 0.8519
Epoch 60/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3327 - accuracy: 0.8621 - val_loss: 0.3557 - val_accuracy: 0.8535
Epoch 61/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3325 - accuracy: 0.8666 - val_loss: 0.3550 - val_accuracy: 0.8519
Epoch 62/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3212 - accuracy: 0.8663 - val_loss: 0.3554 - val_accuracy: 0.8523
Epoch 63/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3302 - accuracy: 0.8646 - val_loss: 0.3546 - val_accuracy: 0.8546
Epoch 64/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3278 - accuracy: 0.8647 - val_loss: 0.3548 - val_accuracy: 0.8542
Epoch 65/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3261 - accuracy: 0.8648 - val_loss: 0.3542 - val_accuracy: 0.8546
Epoch 66/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3249 - accuracy: 0.8697 - val_loss: 0.3549 - val_accuracy: 0.8531
Epoch 67/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3429 - accuracy: 0.8577 - val_loss: 0.3541 - val_accuracy: 0.8557
Epoch 68/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3189 - accuracy: 0.8651 - val_loss: 0.3546 - val_accuracy: 0.8550
Epoch 69/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8634 - val_loss: 0.3553 - val_accuracy: 0.8557
Epoch 70/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3344 - accuracy: 0.8611 - val_loss: 0.3543 - val_accuracy: 0.8569
Epoch 71/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3195 - accuracy: 0.8666 - val_loss: 0.3536 - val_accuracy: 0.8565
Epoch 72/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3227 - accuracy: 0.8645 - val_loss: 0.3543 - val_accuracy: 0.8531
Epoch 73/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3339 - accuracy: 0.8606 - val_loss: 0.3539 - val_accuracy: 0.8535
Epoch 74/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3373 - accuracy: 0.8578 - val_loss: 0.3544 - val_accuracy: 0.8519
Epoch 75/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3205 - accuracy: 0.8666 - val_loss: 0.3529 - val_accuracy: 0.8561
Epoch 76/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3318 - accuracy: 0.8611 - val_loss: 0.3541 - val_accuracy: 0.8546
Epoch 77/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.8582 - val_loss: 0.3540 - val_accuracy: 0.8550
Epoch 78/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3316 - accuracy: 0.8568 - val_loss: 0.3531 - val_accuracy: 0.8538
Epoch 79/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3238 - accuracy: 0.8687 - val_loss: 0.3527 - val_accuracy: 0.8573
Epoch 80/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3225 - accuracy: 0.8681 - val_loss: 0.3534 - val_accuracy: 0.8542
Epoch 81/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3379 - accuracy: 0.8555 - val_loss: 0.3550 - val_accuracy: 0.8565
Epoch 82/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3259 - accuracy: 0.8617 - val_loss: 0.3531 - val_accuracy: 0.8561
Epoch 83/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3193 - accuracy: 0.8696 - val_loss: 0.3531 - val_accuracy: 0.8573
Epoch 84/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8608 - val_loss: 0.3524 - val_accuracy: 0.8554
Epoch 85/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3335 - accuracy: 0.8649 - val_loss: 0.3520 - val_accuracy: 0.8565
Epoch 86/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8592 - val_loss: 0.3520 - val_accuracy: 0.8584
Epoch 87/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3382 - accuracy: 0.8620 - val_loss: 0.3520 - val_accuracy: 0.8595
Epoch 88/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3430 - accuracy: 0.8576 - val_loss: 0.3543 - val_accuracy: 0.8527
Epoch 89/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3567 - accuracy: 0.8510 - val_loss: 0.3526 - val_accuracy: 0.8580
Epoch 90/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3337 - accuracy: 0.8568 - val_loss: 0.3566 - val_accuracy: 0.8535
Epoch 91/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3114 - accuracy: 0.8733 - val_loss: 0.3523 - val_accuracy: 0.8584
Epoch 92/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3264 - accuracy: 0.8641 - val_loss: 0.3526 - val_accuracy: 0.8554
Epoch 93/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3294 - accuracy: 0.8625 - val_loss: 0.3525 - val_accuracy: 0.8554
Epoch 94/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3171 - accuracy: 0.8676 - val_loss: 0.3517 - val_accuracy: 0.8584
Epoch 95/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3244 - accuracy: 0.8649 - val_loss: 0.3526 - val_accuracy: 0.8561
Epoch 96/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3309 - accuracy: 0.8572 - val_loss: 0.3523 - val_accuracy: 0.8569
Epoch 97/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3167 - accuracy: 0.8732 - val_loss: 0.3522 - val_accuracy: 0.8576
Epoch 98/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3301 - accuracy: 0.8613 - val_loss: 0.3513 - val_accuracy: 0.8576
Epoch 99/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3427 - accuracy: 0.8592 - val_loss: 0.3508 - val_accuracy: 0.8576
Epoch 100/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3197 - accuracy: 0.8702 - val_loss: 0.3516 - val_accuracy: 0.8576

In [52]:
# Making the predictions and evaluating the model

#Predicting the Test set results
y_pred=classifier.predict(X_test)
y_pred=(y_pred > 0.5)

In [58]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1504   91]
 [ 192  213]]

In [55]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

In [56]:
score

0.8585